apiVersion: 1

datasources:
  - name: CSV Data
    type: yesoreyeram-infinity-datasource
    uid: csv-data
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      allowedHosts:
        - "http://data-server"
